#!/usr/bin/env python
#-*- coding: utf-8 -*-

import argparse
import os
import sys
import subprocess
import vipy

def argparser():
    parser = argparse.ArgumentParser(description="Vipy text editor")
    return parser

if __name__ == "__main__":
    parser = argparser()
    args = parser.parse_args()
    try:
        screen = vipy.Screen()
        screen.on()
    except:
        process = subprocess.Popen("reset")
